name=input(" what is your name: ")
surname=input(" what is your surname: ")
age=input(" what is your age: ")
color=input(" enter your favorite color: ")
print(color)
car=input(" enter your favorite car brand: ")
print(car)
sport=input(" enter your favorite sport: ")
print=(sport)